apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: consensusai
data:
  PORT: "3000"
  NODE_ENV: "production"
  CORS_ORIGIN: "*"
  # Add other non-sensitive configuration here
