version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ../backend:/app
    ports:
      - "3001:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=3000