apiVersion: apps/v1
kind: Deployment
metadata:
  name: consensusai-client
  namespace: consensusai
  labels:
    app: consensusai-client
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consensusai-client
      tier: frontend
  template:
    metadata:
      labels:
        app: consensusai-client
        tier: frontend
    spec:
      containers:
      - name: consensusai-client
        image: consensusai-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: VITE_API_URL
        - name: VITE_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: consensusai-secrets
              key: VITE_SUPABASE_URL
        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: consensusai-secrets
              key: VITE_SUPABASE_ANON_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
