apiVersion: v1
kind: PersistentVolume
metadata:
  name: consensusai-pv
  labels:
    app: consensusai
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/consensusai-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consensusai-pvc
  namespace: consensusai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
