apiVersion: apps/v1
kind: Deployment
metadata:
  name: consensusai-server
  namespace: consensusai
  labels:
    app: consensusai-server
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consensusai-server
      tier: backend
  template:
    metadata:
      labels:
        app: consensusai-server
        tier: backend
    spec:
      containers:
      - name: consensusai-server
        image: consensusai-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: NODE_ENV
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: CORS_ORIGIN
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: consensusai-secrets
              key: GEMINI_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: consensusai-secrets
              key: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: consensusai-secrets
              key: GEMINI_API_KEY
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: consensusai-secrets
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: consensusai-secrets
              key: SUPABASE_ANON_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
